name: widgetbook_workspace
description: "Widgetbook for Zoe app"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  widgetbook_annotation: ^3.7.0
  widgetbook: ^3.16.0
  flutter_riverpod: ^2.5.1
  flutter_localizations:
    sdk: flutter
  go_router: ^16.2.1
  zoe:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  widgetbook_generator: ^3.16.0

# Added to resolve flutter_quill dependency conflict
dependency_overrides:
  flutter_quill:
    git:
      url: https://github.com/theniceboy/flutter-quill
      ref: 5ff5967

flutter:
  uses-material-design: true


  assets:
    - assets/icon/
    - assets/images/

