// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA67JsuoIJ51o2jvhM4TB8_WCNHcTgo4pA',
    appId: '1:1010784888644:web:91ef143ad5e08e663e9911',
    messagingSenderId: '1010784888644',
    projectId: 'zoe-dev-178cd',
    authDomain: 'zoe-dev-178cd.firebaseapp.com',
    storageBucket: 'zoe-dev-178cd.firebasestorage.app',
    measurementId: 'G-YE6KPE3K1F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVpsv0CaGjEI_7YEai8aizX42nSn2AxIg',
    appId: '1:1010784888644:android:5c5e7c48c4ffe4d83e9911',
    messagingSenderId: '1010784888644',
    projectId: 'zoe-dev-178cd',
    storageBucket: 'zoe-dev-178cd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAT210PnhrV9InxrN1LGrO0Oer4sfsKaok',
    appId: '1:1010784888644:ios:2490933ba2cf03e83e9911',
    messagingSenderId: '1010784888644',
    projectId: 'zoe-dev-178cd',
    storageBucket: 'zoe-dev-178cd.firebasestorage.app',
    iosBundleId: 'app.hellozoe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAT210PnhrV9InxrN1LGrO0Oer4sfsKaok',
    appId: '1:1010784888644:ios:2490933ba2cf03e83e9911',
    messagingSenderId: '1010784888644',
    projectId: 'zoe-dev-178cd',
    storageBucket: 'zoe-dev-178cd.firebasestorage.app',
    iosBundleId: 'app.hellozoe',
  );
}
