// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDADOy17UkkYfISnstMwpz4KrK1iOeSe98',
    appId: '1:762703988712:web:fb010b28b7d6035554465d',
    messagingSenderId: '762703988712',
    projectId: 'zoe-firebase-c9810',
    authDomain: 'zoe-firebase-c9810.firebaseapp.com',
    storageBucket: 'zoe-firebase-c9810.firebasestorage.app',
    measurementId: 'G-G9GQ15FHT5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKmwh8-Ktjdf2aNzeD6QBS6gaqF_zrOYw',
    appId: '1:762703988712:android:6ef1c79ff8a5058f54465d',
    messagingSenderId: '762703988712',
    projectId: 'zoe-firebase-c9810',
    storageBucket: 'zoe-firebase-c9810.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpI_gWGWwFNITccqDjAleRnrX51sImFKM',
    appId: '1:762703988712:ios:81e0fb0f4e1e32cd54465d',
    messagingSenderId: '762703988712',
    projectId: 'zoe-firebase-c9810',
    storageBucket: 'zoe-firebase-c9810.firebasestorage.app',
    iosBundleId: 'app.hellozoe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpI_gWGWwFNITccqDjAleRnrX51sImFKM',
    appId: '1:762703988712:ios:81e0fb0f4e1e32cd54465d',
    messagingSenderId: '762703988712',
    projectId: 'zoe-firebase-c9810',
    storageBucket: 'zoe-firebase-c9810.firebasestorage.app',
    iosBundleId: 'app.hellozoe',
  );

}