[package]
name = "zoe_native"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
flutter_rust_bridge = "=2.11.1"
zoe-client = { workspace = true, features = ["frb-api"] }
zoe-wire-protocol = { workspace = true }
zoe-app-primitives = { workspace = true }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(frb_expand)'] }
