// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../third_party/zoe_client/client.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

abstract class ClientExt {
  /// Create a stream of overall connection status for Flutter Rust Bridge
  ///
  /// This is a Flutter Rust Bridge compatible version that uses StreamSink instead of
  /// returning a Stream directly. It spawns a background task that monitors relay
  /// status changes and sends updates to the provided sink.
  Stream<OverallConnectionStatus> overallStatusStreamFrb();
}
