// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../lib.dart';
import '../third_party/zoe_app_primitives/file/image.dart';
import '../third_party/zoe_app_primitives/group/events/permissions.dart';
import '../third_party/zoe_app_primitives/group/events/settings.dart';
import '../third_party/zoe_app_primitives/group/states.dart';
import '../third_party/zoe_app_primitives/metadata.dart';
import '../third_party/zoe_state_machine/group.dart';
import '../third_party/zoe_state_machine/state.dart';
import '../third_party/zoe_wire_protocol/crypto.dart';
import '../third_party/zoe_wire_protocol/primitives.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Stream<GroupDataUpdate> groupUpdatesStream({required GroupManager manager}) =>
    RustLib.instance.api.crateApiGroupGroupUpdatesStream(manager: manager);
